In [ ]:
#!pip install -r ../requirements.txt
#!pip install pmlb lightgbm
#!python -m pip install -e ..

Collecting pmlb
  Downloading pmlb-1.0.1.post3-py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: pandas>=1.0.5 in /usr/local/lib/python3.12/dist-packages (from pmlb) (2.2.2)
Requirement already satisfied: requests>=2.24.0 in /usr/local/lib/python3.12/dist-packages (from pmlb) (2.32.4)
Requirement already satisfied: pyyaml>=5.3.1 in /usr/local/lib/python3.12/dist-packages (from pmlb) (6.0.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->pmlb) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->pmlb) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->pmlb) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.5->pmlb) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.24.0->pmlb) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.24.0->pmlb) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.24.0->pmlb) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.24.0->pmlb) (2026.1.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.5->pmlb) (1.17.0)
Downloading pmlb-1.0.1.post3-py3-none-any.whl (19 kB)
Installing collected packages: pmlb
Successfully installed pmlb-1.0.1.post3

In [ ]:
import time
from pathlib import Path

import numpy as np
import pandas as pd
from lightgbm import LGBMClassifier
from pmlb import classification_dataset_names, fetch_data
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

from arborration import (
    AADForestGenerativeClassifier,
    IsoForestGenerativeClassifier,
    PineForestGenerativeClassifier,
)

# -------------------------------------------------------------------
# 1) Dataset selection helpers
# -------------------------------------------------------------------

def collect_classification_metadata(max_samples_cap=100_000, max_feats_cap=100):
    """Collect basic metadata for PMLB classification datasets."""
    meta = []
    for name in classification_dataset_names:
        try:
            X, y = fetch_data(name, return_X_y=True)
        except Exception as e:
            print(f"[WARN] Failed to load dataset {name}: {e}")
            continue

        n_samples, n_features = X.shape
        if n_samples < 2:
            continue

        if n_samples > max_samples_cap or n_features > max_feats_cap:
            continue

        n_classes = np.unique(y).shape[0]
        if n_classes < 2:
            continue

        meta.append(
            {
                "name": name,
                "n_samples": n_samples,
                "n_features": n_features,
                "n_classes": n_classes,
            }
        )

    return pd.DataFrame(meta)


def split_into_size_buckets(
    meta_df,
    small_max=1_000,
    med_max=10_000,
    n_small=20,
    n_med=20,
    n_large=20,
    random_state=0,
):
    """Split datasets into small/medium/large buckets and sample each bucket."""
    rng = np.random.RandomState(random_state)

    small = meta_df[meta_df["n_samples"] <= small_max].copy()
    medium = meta_df[
        (meta_df["n_samples"] > small_max) & (meta_df["n_samples"] <= med_max)
    ].copy()
    large = meta_df[meta_df["n_samples"] > med_max].copy()

    def pick(df, n):
        if len(df) <= n:
            return df
        idx = np.arange(len(df))
        rng.shuffle(idx)
        return df.iloc[idx[:n]]

    selected = pd.concat(
        [
            pick(small, n_small).assign(size_bucket="small"),
            pick(medium, n_med).assign(size_bucket="medium"),
            pick(large, n_large).assign(size_bucket="large"),
        ],
        ignore_index=True,
    )
    return selected


# -------------------------------------------------------------------
# 2) AUC helper that handles binary vs multiclass
# -------------------------------------------------------------------

def compute_roc_auc(y_true, proba):
    """Compute ROC AUC for binary or multiclass probability outputs."""
    y_true = np.asarray(y_true)
    proba = np.asarray(proba)

    n_classes = proba.shape[1] if proba.ndim == 2 else 2
    if n_classes == 2:
        return roc_auc_score(y_true, proba[:, 1])

    return roc_auc_score(y_true, proba, multi_class="ovr", average="macro")


# -------------------------------------------------------------------
# 3) Benchmark routine
# -------------------------------------------------------------------

def build_models(n_classes, forest_params=None):
    if forest_params is None:
        forest_params = {
            "n_estimators": 100,
            "max_samples": 256,
            "n_jobs": -1,
            "random_state": 0,
            "verbose": 0,
            "max_depth": None,
            "calibration": "discriminator",
            "global_scale": 1.0,
        }

    models = {
        "GaussianNB": GaussianNB(),
        "LogisticRegression": make_pipeline(
            StandardScaler(),
            LogisticRegression(
                max_iter=1000,
                n_jobs=-1,
                solver="lbfgs",
                multi_class="auto",
                random_state=0,
            ),
        ),
        "IsoForestGenerativeClassifier": IsoForestGenerativeClassifier(**forest_params),
        "PineForestGenerativeClassifier": PineForestGenerativeClassifier(**forest_params),
        "AADForestGenerativeClassifier": AADForestGenerativeClassifier(**forest_params),
    }

    if n_classes == 2:
        models["LGBMClassifier"] = LGBMClassifier(
            n_estimators=200,
            learning_rate=0.1,
            n_jobs=-1,
            random_state=0,
            verbose=-1,
        )
    else:
        models["LGBMClassifier"] = LGBMClassifier(
            n_estimators=200,
            learning_rate=0.1,
            objective="multiclass",
            num_class=n_classes,
            n_jobs=-1,
            random_state=0,
            verbose=-1,
        )

    return models


def benchmark_models_on_datasets(
    dataset_meta,
    test_size=0.3,
    random_state=42,
    forest_params=None,
    verbose=True,
):
    results = []

    for _, row in dataset_meta.iterrows():
        name = row["name"]
        size_bucket = row["size_bucket"]
        n_samples = row["n_samples"]
        n_features = row["n_features"]
        n_classes = row["n_classes"]

        if verbose:
            print(
                f"\n=== Dataset: {name} | bucket={size_bucket} | samples={n_samples} | "
                f"features={n_features} | classes={n_classes} ==="
            )

        try:
            X, y = fetch_data(name, return_X_y=True)
        except Exception as e:
            print(f"[WARN] Skipping dataset {name}, failed to fetch: {e}")
            continue

        try:
            X_train, X_test, y_train, y_test = train_test_split(
                X,
                y,
                test_size=test_size,
                random_state=random_state,
                stratify=y,
            )
        except Exception as e:
            print(f"[WARN] Skipping dataset {name}, train_test_split failed: {e}")
            continue

        models = build_models(n_classes=n_classes, forest_params=forest_params)

        for model_name, model in models.items():
            train_time = np.nan
            infer_time = np.nan
            auc = np.nan

            try:
                t0 = time.perf_counter()
                model.fit(X_train, y_train)
                train_time = time.perf_counter() - t0

                t0 = time.perf_counter()
                proba = model.predict_proba(X_test)
                infer_time = time.perf_counter() - t0

                auc = compute_roc_auc(y_test, proba)
                if verbose:
                    print(f"  {model_name}: roc_auc={auc:.4f}")
            except Exception as e:
                print(f"[WARN] {model_name} failed on {name}: {e}")

            results.append(
                {
                    "dataset": name,
                    "size_bucket": size_bucket,
                    "n_samples": n_samples,
                    "n_features": n_features,
                    "n_classes": n_classes,
                    "model": model_name,
                    "train_time": train_time,
                    "infer_time": infer_time,
                    "roc_auc": auc,
                }
            )

    return pd.DataFrame(results)


# -------------------------------------------------------------------
# 4) Run everything
# -------------------------------------------------------------------

meta_df = collect_classification_metadata(max_samples_cap=100_000)
print(f"Collected metadata for {len(meta_df)} classification datasets.")

selected = split_into_size_buckets(
    meta_df,
    small_max=1_000,
    med_max=10_000,
    n_small=12,
    n_med=12,
    n_large=12,
    random_state=0,
)

print(selected[["name", "size_bucket", "n_samples", "n_features", "n_classes"]])

results_df = benchmark_models_on_datasets(
    selected,
    test_size=0.3,
    random_state=42,
    forest_params=None,
    verbose=True,
)

output_dir = Path("results")
output_dir.mkdir(exist_ok=True)
output_path = output_dir / "forest_generators_vs_baselines_pmlb.csv"
results_df.to_csv(output_path, index=False)
print(f"Saved benchmark results to {output_path}")
results_df.head()

=== Dataset: dermatology | bucket=small | samples=366 | features=34 | classes=6 ===
0.9765527310006715
0.9781901579012563
0.9987106958216798

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

0.9964144391001059

=== Dataset: soybean | bucket=small | samples=675 | features=35 | classes=18 ===
0.9912896729960222
0.9886317142253753
0.9933940874999211

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

0.9974600540165363

=== Dataset: iris | bucket=small | samples=150 | features=4 | classes=3 ===
0.997037037037037
0.997037037037037
0.9985185185185186
0.9918518518518519

=== Dataset: hepatitis | bucket=small | samples=155 | features=19 | classes=2 ===

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

0.8513513513513513
0.9162162162162162
0.7162162162162162
0.7594594594594595

=== Dataset: haberman | bucket=small | samples=306 | features=3 | classes=2 ===

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

0.5701593137254902
0.5683210784313726
0.5946691176470589
0.6369485294117647

=== Dataset: penguins | bucket=small | samples=333 | features=7 | classes=3 ===

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

1.0
0.9993127705627706
1.0
1.0

=== Dataset: cars | bucket=small | samples=392 | features=8 | classes=3 ===

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

0.9206793335592728
0.8827954750827093
0.9134237422991222
0.9865526813475142

=== Dataset: monk2 | bucket=small | samples=601 | features=6 | classes=2 ===

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

0.6676606126321496
0.5359175928435891
0.5458118731363513
0.9615071835185687

=== Dataset: new_thyroid | bucket=small | samples=215 | features=5 | classes=3 ===

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

1.0
1.0
1.0
0.9981369248035915

=== Dataset: corral | bucket=small | samples=160 | features=6 | classes=2 ===

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

0.9982363315696648
0.8465608465608466
0.9400352733686067
1.0

=== Dataset: molecular_biology_promoters | bucket=small | samples=106 | features=57 | classes=2 ===

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

0.9375
0.95703125
0.9140625
0.9921875

=== Dataset: saheart | bucket=small | samples=462 | features=9 | classes=2 ===

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

0.711996336996337
0.7442765567765567
0.7692307692307692
0.6955128205128205

=== Dataset: mfeat_karhunen | bucket=medium | samples=2000 | features=64 | classes=10 ===

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

0.9978240740740741
0.9966481481481482
0.9961296296296297

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

0.9980462962962964

=== Dataset: allhypo | bucket=medium | samples=3770 | features=29 | classes=3 ===
0.7266911758118968
0.6974346418095506
0.94835970167134

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

0.9980700342790169

=== Dataset: page_blocks | bucket=medium | samples=5473 | features=10 | classes=5 ===
0.977302075040383
0.9584793922455503
0.9776127974819488

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

0.9918277378331364

=== Dataset: GAMETES_Epistasis_3_Way_20atts_0.2H_EDM_1_1 | bucket=medium | samples=1600 | features=20 | classes=2 ===
0.5172135416666666
0.5159635416666666
0.5179253472222222
0.6138975694444444

=== Dataset: mfeat_morphological | bucket=medium | samples=2000 | features=6 | classes=10 ===

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

0.9289444444444444
0.9551975308641975
0.9632222222222222

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

0.9485617283950619

=== Dataset: led7 | bucket=medium | samples=3200 | features=7 | classes=10 ===
0.9578561515725393
0.9578084095376628
0.9599349612449265

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

0.9539910028990854

=== Dataset: phoneme | bucket=medium | samples=5404 | features=5 | classes=2 ===
0.8242498570108671
0.8008693005998211
0.7955310396409873

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

0.9459501077918078

=== Dataset: agaricus_lepiota | bucket=medium | samples=8145 | features=22 | classes=2 ===
0.9820498633536208
0.9580765555052563
0.9890790201700115

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

1.0

=== Dataset: coil2000 | bucket=medium | samples=9822 | features=85 | classes=2 ===
0.5126595256061153
0.6426708441324103

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

0.7021997309799547

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

0.696333371608543

=== Dataset: texture | bucket=medium | samples=5500 | features=40 | classes=11 ===
0.9998917171717171
0.9698862626262627

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

0.9999806060606061

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

0.999781414141414

=== Dataset: allhyper | bucket=medium | samples=3771 | features=29 | classes=4 ===
0.7306520213655738
0.705692170125456
0.9526707793505218

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

0.9989130565291051

=== Dataset: mfeat_fourier | bucket=medium | samples=2000 | features=76 | classes=10 ===
0.9752685185185186
0.9616604938271607
0.9732191358024689

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

0.9784814814814815

=== Dataset: adult | bucket=large | samples=48842 | features=14 | classes=2 ===
0.8696720090400079
0.8383910272159771

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

0.8568918315119972

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

0.9297425817746158

=== Dataset: connect_4 | bucket=large | samples=67557 | features=42 | classes=3 ===
0.6441656586141097
0.6124410969510267

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

0.6265098221791779

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

0.9210069886465657

=== Dataset: krkopt | bucket=large | samples=28056 | features=6 | classes=18 ===
0.8630547451243483
0.8289471187085179

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

0.8331684270750038

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

0.7947358665322608

=== Dataset: letter | bucket=large | samples=20000 | features=16 | classes=26 ===
0.9846317952330597
0.9565665519417248

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

0.9807134131438127

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

0.9996771072036643

=== Dataset: magic | bucket=large | samples=19020 | features=10 | classes=2 ===
0.8629855703160789
0.7552295815256932

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

0.8417847807927569

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

0.9349054188784996

=== Dataset: nursery | bucket=large | samples=12958 | features=8 | classes=4 ===
0.913330804650952
0.9049875958280997
0.9151941251489395

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

1.0

=== Dataset: pendigits | bucket=large | samples=10992 | features=16 | classes=10 ===
0.9972430593514788
0.9791138003660544

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

0.9971338336156045

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

0.9994200277835812

=== Dataset: shuttle | bucket=large | samples=58000 | features=9 | classes=7 ===
0.9669463190238412
0.981402314185979

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

0.9581764837624368

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LGBMClassifier was fitted with feature names
  warnings.warn(

0.6532160867042233

Benchmark results (head):
       dataset size_bucket  n_samples  n_features  n_classes  \
0  dermatology       small        366          34          6
1  dermatology       small        366          34          6
2  dermatology       small        366          34          6
3  dermatology       small        366          34          6
4      soybean       small        675          35         18

                model  train_time  infer_time   roc_auc
0                 HRP    0.240293    0.005745  0.976553
1          NaiveBayes    0.012194    0.017239  0.978190
2  LogisticRegression    0.056322    0.005128  0.998711
3      LGBMClassifier    1.270116    0.013645  0.996414
4                 HRP    0.232963    0.015370  0.991290

In [ ]:
#results_df=pd.read_csv('/content/iforest_gen_vs_lr_lgbm_pmlb_benchmark_naive.csv')
non_iso_df=results_df[results_df['model']!='HRP'].copy()

In [ ]:
results_df=pd.concat([non_iso_df,results_df])

In [ ]:
non_iso_df.iloc[:30]

In [ ]:
results_df

In [ ]:
results_df['time_rank']=results_df.groupby('dataset')['train_time'].rank()
results_df.groupby('model')['time_rank'].mean()

model
HRP                   2.15625
LGBMClassifier        3.90625
LogisticRegression    2.93750
NaiveBayes            1.00000
Name: time_rank, dtype: float64

In [ ]:
results_df['time_rank']=results_df.groupby('dataset')['roc_auc'].rank()
results_df.groupby('model')['time_rank'].mean()

model
HRP                   2.515625
LGBMClassifier        3.156250
LogisticRegression    2.656250
NaiveBayes            1.671875
Name: time_rank, dtype: float64

In [ ]:
results_df.loc[results_df.groupby('dataset')['roc_auc'].idxmax()]['model'].value_counts()

model
LGBMClassifier        20
LogisticRegression     7
HRP                    3
NaiveBayes             2
Name: count, dtype: int64

In [ ]:
results_df.loc[results_df.groupby('dataset')['roc_auc'].idxmax()]

,dataset,size_bucket,n_samples,n_features,n_classes,model,train_time,infer_time,roc_auc,time_rank
63,GAMETES_Epistasis_3_Way_20atts_0.2H_EDM_1_1,medium,1600,20,2,LGBMClassifier,0.101287,0.006996,0.613898,4.0
99,adult,large,48842,14,2,LGBMClassifier,0.704878,0.132012,0.929743,4.0
79,agaricus_lepiota,medium,8145,22,2,LGBMClassifier,0.229537,0.017614,1.000000,4.0
91,allhyper,medium,3771,29,4,LGBMClassifier,0.413583,0.040854,0.998913,4.0
55,allhypo,medium,3770,29,3,LGBMClassifier,2.032330,0.058380,0.998070,4.0
27,cars,small,392,8,3,LGBMClassifier,0.096880,0.005127,0.986553,4.0
82,coil2000,medium,9822,85,2,LogisticRegression,1.105015,0.003937,0.702200,4.0
103,connect_4,large,67557,42,3,LGBMClassifier,2.532586,0.577920,0.921007,4.0
39,corral,small,160,6,2,LGBMClassifier,0.015521,0.001653,1.000000,4.0
2,dermatology,small,366,34,6,LogisticRegression,0.056322,0.005128,0.998711,4.0
19,haberman,small,306,3,2,LGBMClassifier,0.095652,0.006223,0.636949,4.0
13,hepatitis,small,155,19,2,NaiveBayes,0.001842,0.000703,0.916216,4.0
10,iris,small,150,4,3,LogisticRegression,0.014587,0.001465,0.998519,4.0
104,krkopt,large,28056,6,18,HRP,0.053085,0.011469,0.863055,4.0
70,led7,medium,3200,7,10,LogisticRegression,0.035041,0.001264,0.959935,4.0
111,letter,large,20000,16,26,LGBMClassifier,12.559200,3.511806,0.999677,4.0
115,magic,large,19020,10,2,LGBMClassifier,0.399131,0.062091,0.934905,4.0
95,mfeat_fourier,medium,2000,76,10,LGBMClassifier,8.016160,0.062703,0.978481,4.0
51,mfeat_karhunen,medium,2000,64,10,LGBMClassifier,4.934164,0.061273,0.998046,4.0
66,mfeat_morphological,medium,2000,6,10,LogisticRegression,0.045877,0.001420,0.963222,4.0
43,molecular_biology_promoters,small,106,57,2,LGBMClassifier,0.047011,0.003454,0.992188,4.0
31,monk2,small,601,6,2,LGBMClassifier,0.040300,0.002991,0.961507,4.0
32,new_thyroid,small,215,5,3,HRP,0.003417,0.000487,1.000000,3.0
119,nursery,large,12958,8,4,LGBMClassifier,0.920006,0.165212,1.000000,4.0
59,page_blocks,medium,5473,10,5,LGBMClassifier,0.819951,0.117248,0.991828,4.0
123,pendigits,large,10992,16,10,LGBMClassifier,3.626803,0.289884,0.999420,4.0
20,penguins,small,333,7,3,HRP,0.004185,0.000525,1.000000,3.0
75,phoneme,medium,5404,5,2,LGBMClassifier,0.185304,0.023233,0.945950,4.0
46,saheart,small,462,9,2,LogisticRegression,0.013603,0.000846,0.769231,4.0
125,shuttle,large,58000,9,7,NaiveBayes,0.013897,0.016214,0.981402,4.0
7,soybean,small,675,35,18,LGBMClassifier,1.692677,0.052795,0.997460,4.0
86,texture,medium,5500,40,11,LogisticRegression,1.319319,0.002801,0.999981,4.0